using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

#pragma warning disable IDE1006 // Naming Styles - off here, because we want to use native names

namespace LockCheck.Linux;

internal static partial class NativeMethods
{
    public const int EAGAIN = 11; // Resource unavailable, try again (same value as EWOULDBLOCK),
    public const int EACCES = 13; // Mandatory lock
    public const int EWOULDBLOCK = EAGAIN; // Operation would block.
    public const int ERANGE = 34;

    public static long GetInode(string path)
    {
        if (Stat(path, out var status) >= 0)
        {
            return status.Ino;
        }

        return -1;
    }

    public static bool TryGetUid(string path, out uint uid)
    {
        if (Stat(path, out var status) >= 0)
        {
            uid = status.Uid;
            return true;
        }

        uid = 0;
        return false;
    }

    public static string? GetUserName(uint uid)
    {
        string? userName;
        unsafe
        {
            const int BufLen = Passwd.InitialBufferSize;
            byte* stackBuf = stackalloc byte[BufLen];
            if (TryGetUserName(uid, stackBuf, BufLen, out userName))
            {
                return userName;
            }

            int lastBufLen = BufLen;
            while (true)
            {
                lastBufLen *= 2;
                byte[] heapBuf = new byte[lastBufLen];
                fixed (byte* buf = &heapBuf[0])
                {
                    if (TryGetUserName(uid, buf, heapBuf.Length, out userName))
                    {
                        return userName;
                    }
                }
            }
        }
    }

    private static unsafe bool TryGetUserName(uint uid, byte* buf, int bufLen, out string? userName)
    {
        int error = GetPwUidR(uid, out Passwd passwd, buf, bufLen);

        // positive error number returned -> failure other than entry-not-found
        if (error != 0)
        {
            userName = null;
            return false;
        }

        // entry not found
        if (error == -1)
        {
            userName = null;
            return true;
        }

        userName = Marshal.PtrToStringAnsi((IntPtr)passwd.Name);
        return true;
    }

    private const string SystemNative = "System.Native";

    [StructLayout(LayoutKind.Sequential)]
    internal struct FileStatus
    {
        internal int Flags;
        internal int Mode;
        internal uint Uid;
        internal uint Gid;
        internal long Size;
        internal long ATime;
        internal long ATimeNsec;
        internal long MTime;
        internal long MTimeNsec;
        internal long CTime;
        internal long CTimeNsec;
        internal long BirthTime;
        internal long BirthTimeNsec;
        internal long Dev;
        internal long RDev;
        internal long Ino;
        internal uint UserFlags;
    }

    [LibraryImport(SystemNative, EntryPoint = "SystemNative_Stat", StringMarshalling = StringMarshalling.Utf8, SetLastError = true)]
    private static partial int Stat(string pathname, out FileStatus status);

    internal unsafe struct Passwd
    {
        internal const int InitialBufferSize = 256;

        internal byte* Name;
        internal byte* Password;
        internal uint UserId;
        internal uint GroupId;
        internal byte* UserInfo;
        internal byte* HomeDirectory;
        internal byte* Shell;
    }

    [LibraryImport(SystemNative, EntryPoint = "SystemNative_GetPwUidR", SetLastError = false)]
    internal static unsafe partial int GetPwUidR(uint uid, out Passwd pwd, byte* buf, int bufLen);

    // TODO: Use this stuff.
    private static readonly HashSet<string> s_critical =
    [
        // List is generated by ChatGPT, obviously ;-)
        "/lib/systemd/systemd",                     // systemd init process (modern distros using systemd)
        "/sbin/init",                               // init process (legacy or minimal distros not using systemd)
        "/usr/sbin/cron",                           // cron scheduler (alternative path)
        "/usr/sbin/crond",                          // cron scheduler (for Red Hat-based systems)
        "/usr/sbin/rsyslogd",                       // syslog daemon (for system logging)
        "/usr/sbin/syslogd",                        // alternative syslog daemon path (legacy or minimal systems)
        "/usr/sbin/sshd",                           // OpenSSH daemon for remote access
        "/usr/lib/NetworkManager/NetworkManager",   // network manager (for desktop/server environments)
        "/sbin/dhcpcd",                             // DHCP client daemon (lightweight systems)
        "/usr/sbin/dhclient",                       // DHCP client daemon (Debian/Ubuntu default)
        "/usr/lib/polkit-1/polkitd",                // policy kit daemon for permissions (common in GUI-based systems)
        "/usr/lib/upowerd",                         // power management daemon (laptops/desktops)
        "/sbin/udevd",                              // udev device manager daemon (general)
        "/usr/lib/udev/udevd",                      // udev device manager daemon (alternative path)
        "/usr/sbin/ntpd",                           // NTP daemon for time synchronization (traditional)
        "/usr/sbin/systemd-timesyncd",              // time sync daemon in systemd environments
        "/usr/sbin/acpid",                          // ACPI daemon for power events (laptop/desktops)
        "/usr/sbin/irqbalance",                     // IRQ balancing daemon (multi-core systems)
        "/usr/sbin/lvmetad",                        // LVM metadata daemon (for managing logical volumes)
        "/sbin/auditd",                             // audit daemon for tracking security events
        "/usr/sbin/firewalld",                      // firewall daemon (often in Red Hat-based systems)
        "/usr/lib/snapd/snapd",                     // snap daemon (Ubuntu, for managing snap packages)
        "/usr/sbin/apparmor",                       // AppArmor security enforcement daemon (Ubuntu-based)
        "/usr/sbin/ModemManager",                   // modem management (often in Linux desktop environments)
        "/usr/sbin/cupsd",                          // CUPS printing service daemon
        "/usr/sbin/bluetoothd",                     // Bluetooth service daemon (for desktops)
        "/usr/libexec/fwupd/fwupd",                 // firmware update daemon (modern desktop systems)
        "/usr/libexec/udisks2/udisksd",             // disk management daemon (common on desktops)
        "/usr/lib/accounts-daemon/accounts-daemon", // user account management daemon (desktops)
        "/usr/sbin/clamd",                          // ClamAV antivirus daemon (for email/AV filtering servers)
        "/usr/bin/Xorg",                            // X server daemon (for X11 display server)
        "/usr/bin/wayland-session",                 // Wayland session daemon (for Wayland display server)
        "/usr/bin/gnome-session",                   // GNOME session manager (often used with Wayland)
        "/usr/libexec/gnome-settings-daemon",       // GNOME settings daemon (for managing user settings)
    ];

    internal static IEnumerable<string> GetKnownCriticalProcesses() => s_critical;

    internal static bool IsProcessCritical(string? executablePath) => executablePath != null && s_critical.Contains(executablePath);
}
