name: Ubuntu

on:
    workflow_dispatch:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build:
      strategy:
        matrix:
          runs-on: ['ubuntu-latest']
          configuration: [Debug, Release]
          dotnet-version: ['8.0.x']
          tfm: ['net8.0']      
      uses: ./.github/workflows/dotnet-reusable-workflow.yml
      with:
        runs-on: ${{ matrix.runs-on }}
        dotnet-version: ${{ matrix.dotnet-version }}
        configuration: ${{ matrix.configuration }}
        tfm: ${{ matrix.tfm }}
        code-coverage: true

    update-coverage-report:
      needs: build
      runs-on: windows-latest
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: coverage-report-net8.0-Release
            path: ubuntu
        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Upload Pages
          uses: actions/upload-pages-artifact@v3        
          with:
            path: ubuntu/coverage-report-net8.0-Release
        - name: Deploy Pages
          id: deployment
          uses: actions/deploy-pages@v4
