name: Ubuntu

on:
    workflow_dispatch:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build:
      strategy:
        matrix:
          runs-on: ['ubuntu-latest']
          configuration: [Debug, Release]
          dotnet-version: ['9.0.x']
          tfm: ['net8.0', 'net9.0']      
      uses: ./.github/workflows/dotnet-reusable-workflow.yml
      with:
        runs-on: ${{ matrix.runs-on }}
        dotnet-version: ${{ matrix.dotnet-version }}
        configuration: ${{ matrix.configuration }}
        tfm: ${{ matrix.tfm }}
        code-coverage: true
