name: DotNet Build Windows

on:
    # Allow to use "gh.exe workflow run Windows --ref <branchname>" to trigger this workflow for arbitrary branches.
    workflow_dispatch:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
  
jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                runs-on: ['windows-latest']
                configuration: [Debug, Release]
                dotnet-version: ['8.0.x']
                tfm: ['net8.0', 'net481']
        steps:
            - name: Build
              uses: ./.github/workflows/dotnet-reusable-workflow.yml
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
                configuration: ${{ matrix.configuration }}
                tfm: ${{ matrix.tfm }}