name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnet-version: ['8.0.x']
        tfm: ['net8.0']

    runs-on: windows-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so that nbgv can do its work.
    - name: Setup .NET (64 bit)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: List Runtimes 64 bit
      run: cmd /c "C:\Program Files\dotnet\dotnet.exe" --list-runtimes
    - name: List Runtimes 32 bit
      run: cmd /c "C:\Program Files (x86)\dotnet\dotnet.exe" --list-runtimes
    - name: Build
      run: dotnet build -f ${{ matrix.tfm }} -c ${{ matrix.configuration }}
    - name: Test
      run: dotnet test --no-build -f ${{ matrix.tfm }} -d "TestResults-${{ matrix.tfm }}-${{ matrix.configuration }}\diag.log" -v d -c ${{ matrix.configuration }} -l trx --results-directory "TestResults-${{ matrix.tfm }}-${{ matrix.configuration }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.tfm }}-${{ matrix.configuration }}
        path: TestResults-${{ matrix.tfm }}-${{ matrix.configuration }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}